# Generated by Django 4.2.18 on 2025-01-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonk_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonkprofile',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonkprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
